In [1]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import  LinearSVC


## linear classification

In [2]:
svm_clf =  Pipeline([("scaler",StandardScaler()),
                    ("linear_svc",LinearSVC(C=1,loss = "hinge"))
                    ])

In [3]:
iris = datasets.load_iris()
x = iris["data"][:,(2,3)]
y = (iris["target"] == 2).astype(np.float64)

In [4]:
svm_clf.fit(x,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [5]:
svm_clf.predict([[5.5,1.7]])

array([1.])

In [6]:
from sklearn.svm import SVC
clf = SVC(kernel = "linear",C=1)
clf.fit(x,y)
clf.predict([[5.5,1.7]])

array([1.])

In [7]:
from sklearn.linear_model import SGDClassifier
clf1 = SGDClassifier(loss = "hinge")
clf1.fit(x,y)
clf1.predict([[5.5,1.7]])

array([1.])

## non linear svm classification

In [8]:
#using poylnomial features
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures
x,y = make_moons(n_samples = 100,noise = 0.15)
polynomial_svm_clf = Pipeline([
    ("poly_features",PolynomialFeatures(degree = 3)),
    ("scaler",StandardScaler()),
    ("cm_clf",LinearSVC(C = 10,loss= "hinge"))])
    
polynomial_svm_clf.fit(x,y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('cm_clf', LinearSVC(C=10, loss='hinge'))])

In [9]:
poly_kernel_svm = Pipeline([
    ("scaler",StandardScaler()),
    ("svm_clf",SVC(kernel ="poly",degree = 3,coef0 = 1,C=5 ))
])
poly_kernel_svm.fit(x,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

In [10]:
#using similarity features
rbf_kernel_svm = Pipeline([
    ("scaler",StandardScaler()),
    ("svm_clf",SVC(kernel ="rbf",gamma  = 5,C=0.0001 ))
])
rbf_kernel_svm.fit(x,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=0.0001, gamma=5))])

## svm regression

In [11]:
from sklearn.svm  import LinearSVR
svm_reg = LinearSVR(epsilon = 1.5)
svm_reg.fit(x,y)

LinearSVR(epsilon=1.5)

In [12]:
from sklearn.svm  import SVR
svm_reg = SVR(kernel = "poly",degree = 2,epsilon = 0.1)
svm_reg.fit(x,y)

SVR(degree=2, kernel='poly')

## exercises

In [13]:
# 8 train a linear svcon alipnearly seperable dataset then train an SVC and a SGD Classifier on the same 
#dataset .see if you can get them to produce roughly same dataset

In [14]:
from sklearn import datasets
iris = datasets.load_iris()


In [15]:
x = iris["data"][:,(2,3)]
y = iris["target"]


In [16]:
# y has three values but we need only two for linear svc so let's  1 and 2

In [17]:
x = x[(y ==1) |(y==2)]


In [18]:
y = y[(y ==1) |(y==2)]

In [19]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


In [20]:
#alpha = 1/c*len(x)
s = StandardScaler()
x_scaled = s.fit_transform(x)
svc_clf = LinearSVC(loss = "hinge",C = 1,random_state = 43)
svc_clf1 = SVC(kernel = "linear",C = 1)
svc_clf2 = SGDClassifier(alpha = 1/1*len(x),learning_rate = "constant",eta0 =0.001,random_state = 42)

In [21]:
svc_clf.fit(x_scaled,y)
svc_clf1.fit(x_scaled,y)
svc_clf2.fit(x_scaled,y)

SGDClassifier(alpha=100.0, eta0=0.001, learning_rate='constant',
              random_state=42)

In [22]:
print((svc_clf.intercept_,svc_clf.coef_))
print((svc_clf1.intercept_,svc_clf1.coef_))
print((svc_clf2.intercept_,svc_clf2.coef_))

(array([0.19638279]), array([[1.49370756, 1.53675533]]))
(array([0.19631477]), array([[1.49339003, 1.53672846]]))
(array([0.]), array([[0.00684812, 0.0087194 ]]))


In [23]:
# lets plot all three decision boundaries

In [24]:
## doubt 

In [25]:
'''# Compute the slope and bias of each decision boundary
w1 = -lin_clf.coef_[0, 0]/lin_clf.coef_[0, 1]
b1 = -lin_clf.intercept_[0]/lin_clf.coef_[0, 1]
w2 = -svm_clf.coef_[0, 0]/svm_clf.coef_[0, 1]
b2 = -svm_clf.intercept_[0]/svm_clf.coef_[0, 1]
w3 = -sgd_clf.coef_[0, 0]/sgd_clf.coef_[0, 1]
b3 = -sgd_clf.intercept_[0]/sgd_clf.coef_[0, 1]

# Transform the decision boundary lines back to the original scale
line1 = scaler.inverse_transform([[-10, -10 * w1 + b1], [10, 10 * w1 + b1]])
line2 = scaler.inverse_transform([[-10, -10 * w2 + b2], [10, 10 * w2 + b2]])
line3 = scaler.inverse_transform([[-10, -10 * w3 + b3], [10, 10 * w3 + b3]])

# Plot all three decision boundaries
plt.figure(figsize=(11, 4))
plt.plot(line1[:, 0], line1[:, 1], "k:", label="LinearSVC")
plt.plot(line2[:, 0], line2[:, 1], "b--", linewidth=2, label="SVC")
plt.plot(line3[:, 0], line3[:, 1], "r-", label="SGDClassifier")
plt.plot(X[:, 0][y==1], X[:, 1][y==1], "bs") # label="Iris versicolor"
plt.plot(X[:, 0][y==0], X[:, 1][y==0], "yo") # label="Iris setosa"
plt.xlabel("Petal length", fontsize=14)
plt.ylabel("Petal width", fontsize=14)
plt.legend(loc="upper center", fontsize=14)
plt.axis([0, 5.5, 0, 2])

plt.show()'''

'# Compute the slope and bias of each decision boundary\nw1 = -lin_clf.coef_[0, 0]/lin_clf.coef_[0, 1]\nb1 = -lin_clf.intercept_[0]/lin_clf.coef_[0, 1]\nw2 = -svm_clf.coef_[0, 0]/svm_clf.coef_[0, 1]\nb2 = -svm_clf.intercept_[0]/svm_clf.coef_[0, 1]\nw3 = -sgd_clf.coef_[0, 0]/sgd_clf.coef_[0, 1]\nb3 = -sgd_clf.intercept_[0]/sgd_clf.coef_[0, 1]\n\n# Transform the decision boundary lines back to the original scale\nline1 = scaler.inverse_transform([[-10, -10 * w1 + b1], [10, 10 * w1 + b1]])\nline2 = scaler.inverse_transform([[-10, -10 * w2 + b2], [10, 10 * w2 + b2]])\nline3 = scaler.inverse_transform([[-10, -10 * w3 + b3], [10, 10 * w3 + b3]])\n\n# Plot all three decision boundaries\nplt.figure(figsize=(11, 4))\nplt.plot(line1[:, 0], line1[:, 1], "k:", label="LinearSVC")\nplt.plot(line2[:, 0], line2[:, 1], "b--", linewidth=2, label="SVC")\nplt.plot(line3[:, 0], line3[:, 1], "r-", label="SGDClassifier")\nplt.plot(X[:, 0][y==1], X[:, 1][y==1], "bs") # label="Iris versicolor"\nplt.plot(X[:, 0

In [26]:
'''Exercise: train an SVM classifier on the MNIST dataset. Since SVM classifiers are binary classifiers, you will need to use one-versus-all to classify all 10 digits. You may want to tune the hyperparameters using small validation sets to speed up the process. What accuracy can you reach?'''

'Exercise: train an SVM classifier on the MNIST dataset. Since SVM classifiers are binary classifiers, you will need to use one-versus-all to classify all 10 digits. You may want to tune the hyperparameters using small validation sets to speed up the process. What accuracy can you reach?'

In [27]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784',version = 1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [28]:
x,y = mnist["data"],mnist["target"].astype("uint")
x

In [29]:
# let's spllit the data manually that would be better to check performance of different models
#shuffle if the data is not already
x_train,x_test,y_train,y_test = x[:60000],x[60000:],y[:60000],y[60000:]
ls = LinearSVC()
ls.fit(x_train,y_train)


c:\users\govind\appdata\local\programs\python\python38\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [30]:
from sklearn.metrics import accuracy_score
y_pred = ls.predict(x_train)
accuracy_score(y_train,y_pred)

0.8825833333333334

In [31]:
#88% accuracy is pretty bad maybe we need to scale the data

In [32]:
s1 = StandardScaler()
x_scaled = s1.fit_transform(x_train)
x_ts = s1.fit_transform(x_test)
ls.fit(x_scaled,y_train)
y_pred = ls.predict(x_scaled)
accuracy_score(y_train,y_pred)

c:\users\govind\appdata\local\programs\python\python38\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.9203666666666667

In [33]:
scm_clf = SVC()
scm_clf.fit(x_scaled[:10000],y_train[:10000])
y_pred = scm_clf.predict(x_scaled)
accuracy_score(y_train,y_pred)

0.9455333333333333

In [ ]:
#tune the hyperparameter  using randomized search 
#take small dataset to fasten up the process

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import  uniform

param_distributions = {"gamma": uniform(0.1, 0.5), "C": uniform(1, 10)}
rnd_search_cv = RandomizedSearchCV(scm_clf, param_distributions, n_iter=10, verbose=2, cv=3)
rnd_search_cv.fit(x_scaled[:1000], y_train[:1000])


In [ ]:
rnd_search_cv.best_estimator_

In [ ]:
rnd_search_cv.best_score_

In [ ]:
rnd_search_cv.best_estimator_.fit(x_scaled, y_train)

In [ ]:
y_pred = rnd_search_cv.best_estimator_.predict(X_scaled)
accuracy_score(y_train, y_pred)


In [ ]:
y_pred = rnd_search_cv.best_estimator_.predict(X_ts)
accuracy_score(y_test, y_pred)

In [ ]:
#Q10

In [ ]:
'''Exercise: train an SVM regressor on the California housing dataset.

Let's load the dataset using Scikit-Learn's fetch_california_housing() function:'''

In [ ]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
X = housing["data"]
y = housing["target"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.svm import LinearSVR

lin_svr = LinearSVR(random_state=42)
lin_svr.fit(X_train_scaled, y_train)

In [ ]:
from sklearn.metrics import mean_squared_error

y_pred = lin_svr.predict(X_train_scaled)
mse = mean_squared_error(y_train, y_pred)
mse

In [ ]:
np.sqrt(mse)

In [ ]:
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import reciprocal, uniform

param_distributions = {"gamma": reciprocal(0.001, 0.1), "C": uniform(1, 10)}
rnd_search_cv = RandomizedSearchCV(SVR(), param_distributions, n_iter=10, verbose=2, cv=3, random_state=42)
rnd_search_cv.fit(X_train_scaled, y_train)

In [ ]:
rnd_search_cv.best_estimator_

In [ ]:
y_pred = rnd_search_cv.best_estimator_.predict(X_train_scaled)
mse = mean_squared_error(y_train, y_pred)
np.sqrt(mse)

In [ ]:
y_pred = rnd_search_cv.best_estimator_.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
np.sqrt(mse)